version: "3.8"

services:

  consumer:
    image: openjdk:17-jdk-slim-buster
    environment:
      OTEL_SERVICE_NAME: consumer
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      OTEL_METRICS_EXPORTER: prometheus
      WEB_HTTP_PORT: 9191
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 9192
      WEB_HTTP_MANAGEMENT_PATH: /api/v1/management
      WEB_HTTP_IDS_PORT: 9292
      WEB_HTTP_IDS_PATH: /api/v1/ids
      IDS_WEBHOOK_ADDRESS: http://consumer:9292
      EDC_API_AUTH_KEY: password
    volumes:
      - ../:/samples
    ports:
      - "9191:9191"
      - "9192:9192"
    entrypoint: java
      -javaagent:/samples/transfer-04-open-telemetry/opentelemetry-javaagent.jar
      -Djava.util.logging.config.file=/samples/transfer-04-open-telemetry/logging.properties
      -jar /samples/transfer-04-open-telemetry/open-telemetry-consumer/build/libs/consumer.jar

  provider:
    image: openjdk:17-jdk-slim-buster
    environment:
      OTEL_SERVICE_NAME: provider
      OTEL_TRACES_EXPORTER: jaeger
      OTEL_EXPORTER_JAEGER_ENDPOINT: http://jaeger:14250
      WEB_HTTP_PORT: 8181
      WEB_HTTP_PATH: /api
      WEB_HTTP_MANAGEMENT_PORT: 8182
      WEB_HTTP_MANAGEMENT_PATH: /api/v1/management
      IDS_WEBHOOK_ADDRESS: http://provider:8282
      EDC_SAMPLES_TRANSFER_01_ASSET_PATH: /samples/transfer-04-open-telemetry/input-file.txt
    volumes:
      - ../:/samples
    ports:
      - "8181:8181"
      - "8182:8182"
    entrypoint: java
      -javaagent:/samples/transfer-04-open-telemetry/opentelemetry-javaagent.jar
      -Djava.util.logging.config.file=/samples/transfer-04-open-telemetry/logging.properties
      -jar /samples/transfer-04-open-telemetry/open-telemetry-provider/build/libs/provider.jar

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 16686:16686

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - 9090:9090
